spring:
  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/greatstep
    password: djljgfL1250
    username: greatstep
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
